### ISSUE TITLE
Option to filter data from Becker Léon

### ISSUE THREAD

**Issue by niconoe** [niconoe/arabel#1]
Very old data (Becker) are uncertain and it would be better if we'e able to distinguish those from the rest of the database.

Rather than showing them in a different color on the map (which could conflict with the square color scale, once implemented), I suggest adding a checkbox next to the species selection list.

**Comment by niconoe** [comment]
Question for Frederick:

- How can I identify the data to filter out in the database? I suspect it's when I found a reference to "Léon Becker" in "Leg" (or is it "Det") in the "STAAL GEGEVENS" table, correct? 
- In that case, I noticed multiple name variants that probably (?) refers to this same person: "Becker Léon", "Becker Leon", "Becker L.", ... I guess they all should be filtered out? Other spellings you're aware of?

**Comment by fhendric** [comment]
Indeed, these do all refer to the same person. We could make a list of issues that need to be changed in the database itself and incorporate these changes ourselves and then provide you with a new version.

**Comment by niconoe** [comment]
Thanks @fhendric!

As you suggest, I'll filter in the app only with the "Becker Leon" spelling, and you 'll provide me a new version of the database with all spellings fixed!

Long-term suggestion for a cleaner database: create a new table (`MENSEN`?) with at least the following fields: `first_name`, `last_name` and `id`), move all the distinct people known in the database there, and refers to it from all the other tables using a foreign key. Once done, remove the redundant information (drop the now-redundant text fields in various tables that now have a foreign key to mensen).

**Comment by fhendric** [comment]
There you have it 😊

**Comment by niconoe** [comment]
That's now implemented, don't hesitate to comment!
