### ISSUE TITLE
Other map backgrounds and overlays

### ISSUE THREAD

**Issue by niconoe** [niconoe/arabel#5]
- Ecoregions
- Satellite background (free providers for those?)
- Maybe other overlays (inspiration on formicidae-atlas.be)

**Comment by niconoe** [comment]
@fhendric:

I just added ecoregions and a few others. They can be activated by using the icon in the top-right corner of the map. 

Can you have a look and comment?

thanks a lot

**Comment by fhendric** [comment]
Perfect Nico! Thanks.

frederik
