### ISSUE TITLE
Improve species selector

### ISSUE THREAD

**Issue by niconoe** [niconoe/arabel#6]
- Order species per alphabetical order 
- Maybe later: also an option to group by family?
- Type-ahead feature (is the browser enough or should we use a custom form field?)

**Comment by niconoe** [comment]
It's now ordered (5e35b086dbeb47df98b3fa51f45a894f7b61a122)

**Comment by niconoe** [comment]
TODO: check with Frederick/Wouter if it's good like this of if we need a more sophisticated approach for the type ahead / list filtering (basic type ahead already provided by the browser).

**Comment by niconoe** [comment]
Frederick, can you have a look at the improvements and tell me if it's ok?

**Comment by fhendric** [comment]
Looks very fine to me.
