### ISSUE TITLE
Option to show "red list" status

### ISSUE THREAD

**Issue by niconoe** [niconoe/arabel#9]
Where: on top of page, after search (more metadata on species?)
Apparently, those species are already flagged in the database

**Comment by niconoe** [comment]
Question for Frederick:

- I guess this data can be identified using the columns "RL" and "RL-C" in the source SOORTEN INFO table, correct?
- If yes, should I only show in the interface that a species is on the red list (RL column contains the "RL" value), or should I actually give more details (for example display "vulnerable" if the RL-C column contains the "VU" value)?

**Comment by fhendric** [comment]
The best option would be to add the full English name of the status ("vulnerable" in case of VU). I noticed that there is a table in the database that contains a description of the red list categories ("Omschrijving rode lijst categoriën), but only in Dutch. I translated them and you could adjust the table by adding a column "Description" in this table and use those terminologies (I did the same such that it remains compatible):

R-L (ci) | Omschrijving | Description
-- | -- | --
0 | Uitgestorven | Extinct
1 | Met uitsterven bedreigd | Critically endangered
2 | Bedreigd | Endangered
3 | Kwetsbaar | Vulnerable
4 | Onvoldoende gekend | Data Deficient
5 | Zeldzaam | Rare
6 | Momenteel niet bedreigd | Least concern
7 | Nieuw voor België | Not evaluated
8 | Nog opzoeken!!! | Not evaluated

**Comment by niconoe** [comment]
Thanks @fhendric, I am currently implementing this as suggested. 

Here are a few suggestions for a better long-term database structure (not needed for me, but good practices for a clean database on the long run).

Since you have a table dedicated to the description of the categories (Omschrijving rode lijst categoriën), use it to store all "status related data":
   - remove all redundant data in other SOORTEN_INFO columns (`RLC-E`, `RL-C`, ...) and only express the status via the `RL-C (ci)` foreign key (one day or another, the data will become inconsistent between all those columns)
   - add more colums (abbreviations in multiple languages for example) to the `Omschrijving rode lijst categoriën`
   - Add a real Access foreign key to this relationship (so Access will prevent you to accidentaly reference a non-existing red list status in `SOORTEN INFO`
   - Consider changing `Omschrijving rode lijst categoriën` to uppercase so it's clear to users its a proper, long-term data table (not something temporary to be dropped at the first occasion) (please inform me if you do so, I'll need to update my code)
   - Consider renaming the `RL-C (ci)` so the name is more less abbreviated and therefore explicitly understandable to a new person (someting along the line of `redlist_status_id`?). Maybe also consider renaming the reference table for consistency (`REDLIST_STATUS`?) (please inform me if you do so, I'll need to update my code)

BTW: general question: are you interested in those king of database architecture comments? Or do you prefer to keep it as it is for now?

**Comment by fhendric** [comment]
Dear Nico,

Sure, this kind of suggestions are definitely useful! We realize that the current database structure is not ideal. It started about 25 years ago and we had hardly any idea as arachnologists what a database actually is and only knew that Access could be used for it 😊. Luckily, we implemented quite early the structure of the three basic tables, but the relational aspect of the database can definitely be improved.
Although we will definitely keep the basic structure, also to avoid any import issues when the data need to be important into your interface, it is very good to receive suggestions of any kind to improve the database. Some other improvements that would be very welcome I think is to have separate tables for the municipalities, area’s, leg and det as these columns are currently very messy (doubles, misspellings, etc, etc..), which is very unfortunate. But like always, finding the time to better implement these columns is the most difficult one 😊.

Cheers,

frederik
